version: "2"
services:
  csp1_producer:
    build: ./csp1_producer
    volumes:
      - ./csp1_producer.properties:/app/app.properties
    network_mode: host
    depends_on:
      - broker
  csp1_consumer:
    build: ./csp1_consumer
    volumes:
      - ./csp1_consumer.properties:/app/app.properties
    network_mode: host
    depends_on:
      - broker
  csp1_transformer:
    build: ./csp1_transformer
    volumes:
      - ./csp1_transformer.properties:/app/app.properties
    network_mode: host
    depends_on:
      - broker
  csp2_producer:
    build: ./csp2_producer
    volumes:
      - ./csp2_producer.properties:/app/app.properties
    network_mode: host
    depends_on:
      - broker
  csp2_transformer:
    build: ./csp2_transformer
    volumes:
      - ./csp2_transformer.properties:/app/app.properties
    network_mode: host
    depends_on:
      - broker
  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard.properties:/app/app.properties
    network_mode: host
    depends_on:
      - broker
  zookeeper:
    image: solsson/kafka:latest
    network_mode: host
    entrypoint: ./bin/zookeeper-server-start.sh
    command:
      - ./config/zookeeper.properties
  broker:
    image: solsson/kafka:latest
    network_mode: host
    entrypoint: ./bin/kafka-server-start.sh
    depends_on:
      - zookeeper
    command:
      - ./config/server.properties