apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: csp1-transformer
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: csp1-transformer
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: csp1.transactions
          patternType: literal
        operations:
          - Read
        host: "*"
      - resource:
          type: topic
          name: transactions
          patternType: literal
        operations:
          - Write
        host: "*"
      - resource:
          type: transactionalId
          name: transactions-transformer-app
          patternType: literal
        operations:
          - Describe
          - Write
      - resource:
          type: cluster
          name: kafka-cluster
          patternType: literal
        operations:
          - IdempotentWrite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csp1-transformer
  labels:
    app: example-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-project
  template:
    metadata:
      labels:
        app: example-project
    spec:
      containers:
        - name: csp1-transformer
          image: ghcr.io/kafka-trainings/example-project/csp1_transformer:latest
          imagePullPolicy: Always
          ports:
            - name: jmx
              containerPort: 3013
          volumeMounts:
            - name: user-certs
              mountPath: /tls/user.p12
              subPath: user.p12
            - name: cluster-certs
              mountPath: /tls/ca.p12
              subPath: ca.p12
            - name: config
              mountPath: /app/app.properties
              subPath: app.properties
          env:
            # SSL Configs
            - name: KAFKA_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csp1-transformer
                  key: user.password
            - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-cluster-ca-cert
                  key: ca.password
      volumes:
        - name: user-certs
          secret:
            secretName: csp1-transformer
        - name: cluster-certs
          secret:
            secretName: kafka-cluster-ca-cert
        - name: config
          configMap:
            name: csp1-transformer-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csp1-transformer-config
data:
  app.properties: |
    bootstrap.servers=kafka-kafka-bootstrap:9093
    csp1.topic=csp1.transactions
    output.topic=transactions
    group.id=csp1-transformer
    transactional.id=transactions-transformer-app
    processing.time.ms=1000
    app.log.infos=true
    client.id=csp1-transformer
    security.protocol=SSL
    ssl.keystore.location=/tls/user.p12
    ssl.truststore.location=/tls/ca.p12