apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: csp1.producer
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: csp1.transactions
          patternType: literal
        operations:
          - Write
        host: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csp1-producer
  labels:
    app: csp1-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csp1-producer
  template:
    metadata:
      labels:
        app: csp1-producer
    spec:
      containers:
        - name: csp1-producer
          image: ghcr.io/kafka-trainings/example-project/csp1_producer:latest
          imagePullPolicy: Always
          ports:
            - name: jmx
              containerPort: 3011
          volumeMounts:
            - name: user-certs
              mountPath: /tls/user.p12
              subPath: user.p12
            - name: cluster-certs
              mountPath: /tls/ca.p12
              subPath: ca.p12
            - name: config
              mountPath: /app/app.properties
              subPath: app.properties
          env:
            # SSL Configs
            - name: KAFKA_SECURITY_PROTOCOL
              value: SSL
            - name: KAFKA_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csp1.producer
                  key: user.password
            - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-cluster-ca-cert
                  key: ca.password
      volumes:
        - name: user-certs
          secret:
            secretName: csp1.producer
        - name: cluster-certs
          secret:
            secretName: kafka-cluster-ca-cert
        - name: config
          configMap:
            name: csp1-producer-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csp1-producer-config
data:
  app.properties: |
    bootstrap.servers=kafka-kafka-bootstrap:9093
    topic=csp1.transactions
    producer.msgs.per.sec=1
    app.log.infos=true
    client.id=csp1_producer
    security.protocol=SSL
    ssl.keystore.location=/tls/user.p12
    ssl.truststore.location=/tls/ca.p12