apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: csp1-consumer
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: csp1-consumer
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: csp1.transactions
          patternType: literal
        operations:
          - Read
        host: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csp1-consumer
  labels:
    app: example-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-project
  template:
    metadata:
      labels:
        app: example-project
    spec:
      containers:
        - name: csp1-consumer
          image: ghcr.io/kafka-trainings/example-project/csp1_consumer:latest
          imagePullPolicy: Always
          ports:
            - name: jmx
              containerPort: 3012
          volumeMounts:
            - name: user-certs
              mountPath: /tls/user.p12
              subPath: user.p12
            - name: cluster-certs
              mountPath: /tls/ca.p12
              subPath: ca.p12
            - name: config
              mountPath: /app/app.properties
              subPath: app.properties
          env:
            # SSL Configs
            - name: KAFKA_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csp1-consumer
                  key: user.password
            - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-cluster-ca-cert
                  key: ca.password
      volumes:
        - name: user-certs
          secret:
            secretName: csp1-consumer
        - name: cluster-certs
          secret:
            secretName: kafka-cluster-ca-cert
        - name: config
          configMap:
            name: csp1-consumer-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csp1-consumer-config
data:
  app.properties: |
    bootstrap.servers=kafka-kafka-bootstrap:9093
    topic=csp1.transactions
    group.id=csp1-consumer
    app.log.infos=true
    client.id=csp1-consumer
    security.protocol=SSL
    ssl.keystore.location=/tls/user.p12
    ssl.truststore.location=/tls/ca.p12