apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: csp2.producer
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: csp2.transactions
          patternType: literal
        operations:
          - Write
        host: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csp2-producer
  labels:
    app: csp2-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csp2-producer
  template:
    metadata:
      labels:
        app: csp2-producer
    spec:
      containers:
        - name: csp2-producer
          image: ghcr.io/kafka-trainings/example-project/csp2_producer:latest
          imagePullPolicy: Always
          ports:
            - name: jmx
              containerPort: 3021
          volumeMounts:
            - name: user-certs
              mountPath: /tls/user.p12
              subPath: user.p12
            - name: cluster-certs
              mountPath: /tls/ca.p12
              subPath: ca.p12
          env:
            # Replace ConfigMap by Environment
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-kafka-bootstrap:9093
            - name: KAFKA_TOPIC
              value: csp2.transactions
            - name: KAFKA_PRODUCER_BATCH_INTERVAL_S
              value: "10"
            - name: KAFKA_PRODUCER_MSGS_PER_BATCH
              value: "100"
            - name: KAFKA_CLIENT_ID
              value: csp2.producer
            - name: KAFKA_APP_LOG_INFOS
              value: "true"
            # SSL Configs
            - name: KAFKA_SECURITY_PROTOCOL
              value: SSL
            - name: KAFKA_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csp2.producer
                  key: user.password
            - name: KAFKA_SSL_KEYSTORE_LOCATION
              value: /tls/user.p12
            - name: KAFKA_SSL_TRUSTSTORE_LOCATION
              value: /tls/ca.p12
            - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-cluster-ca-cert
                  key: ca.password
      volumes:
        - name: user-certs
          secret:
            secretName: csp2.producer
        - name: cluster-certs
          secret:
            secretName: kafka-cluster-ca-cert