apiVersion: apps/v1
kind: Deployment
metadata:
  name: csp2-producer
  labels:
    app: csp2-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csp2-producer
  template:
    metadata:
      labels:
        app: csp2-producer
    spec:
      containers:
        - name: csp2-producer
          image: ghcr.io/kafka-trainings/example-project/csp2_producer:latest
          imagePullPolicy: Always
          ports:
            - name: jmx
              containerPort: 3021
          volumeMounts:
            - name: config
              mountPath: /app/app.properties
              subPath: app.properties
      volumes:
        - name: config
          configMap:
            name: csp2-producer-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csp2-producer-config
data:
  app.properties: |
    bootstrap.servers=kafka-kafka-bootstrap:9092
    topic=csp2_transactions
    producer.batch_interval.s=10
    producer.msgs_per_batch=100
    app.log.infos=true
    client.id=csp2_producer