apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: csp1.transactions
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 12
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transactions
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 12
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: csp2.transactions
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 12
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: csp2.customer.id.mapping
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 12
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: csp2.chargingstation.id.mapping
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 12
  replicas: 3
---